version: "3.7"
services:
    app:
        build:
            args:
                user: hn
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: leitner
        container_name: leitner-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - db
        networks:
            - leitner-net

    db:
        image: mysql:latest
        container_name: leitner-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - 3306:3306
        volumes:
          - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - leitner-net
    nginx:
        image: nginx:alpine
        container_name: leitner-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - leitner-net

networks:
    leitner-net:
        driver: bridge

